### ISSUE TITLE
Note: If you want to show deployments in PRs / pull requests, pass `ref`

### ISSUE THREAD

**Issue by tony** [chrnorm/deployment-status#29]
Want this?

![image](https://user-images.githubusercontent.com/26336/135450127-ef5d4a3d-a240-4d7c-9808-b74b472e1600.png)

Pass your branch name to ref `ref: <your branch>``

Looks like this:

```yaml
name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  deployment:
    steps:
      - name: Get git output names
        id: git
        shell: bash
        run: |
          if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
            if [[ ${{ github.event_name }} == 'pull_request' ]]; then
              echo "::set-output name=current_branch::$HEAD_REF"
            else
              echo "::set-output name=current_branch::$REF_BRANCH"
            fi
          else
            REF=$(printf "%q" "${{ github.ref }}")
            REF_BRANCH=${REF/refs\/tags\/${{ inputs.strip_tag_prefix }}/}
            echo "::set-output name=current_branch::$(eval printf "%s" "$REF_BRANCH")"
          fi
  
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-app-url.com
          environment: production
          ref: ${{ steps.git.outputs.current_branch }}
  
      - name: Deploy my app
        run: |
          # add your deployment code here
  
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: http://my-app-url.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          ref: ${{ steps.git.outputs.current_branch }}
  
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: http://my-app-url.com
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          ref: ${{ steps.git.outputs.current_branch }}
```

In practice, I used a fork with @jimCresswell's change at #26

**Comment by chrnorm** [comment]
Thanks for this @tony! I've pinned this issue for visibility.

**Comment by matteovivona** [comment]
Right now, you don't need to specify `ref` option. 
With v2.0.1 you just need to specify these options here:

```
      - name: Updates deployment status
        uses: chrnorm/deployment-status@v2.0.1
        with:
          state: "in_progress"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          token: ${{ secrets.PAT }}
          environment: production
          environment-url: https://github.com
```
