### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by selfagency** [chrnorm/deployment-status#31]
For some reason, starting a deployment works fine, but updating a deployment fails for me

```yaml
      - name: Finalize GitHub deployment
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ steps.status.outputs.status }}
          deployment_id: ${{ needs.setup.outputs.deployment_id }}
```

```sh
Run chrnorm/deployment-status@releases/v1
  with:
    token: ***
    state: failure
    deployment_id: 51057
  env:
    ENVIRONMENT: staging
    BACKEND: true
    FRONTEND: true
    DISPATCH: true
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```
