### ISSUE TITLE
Too wide scope for deployments marked as inactive

### ISSUE THREAD

**Issue by mateuszgorniak** [chrnorm/deployment-status#45]
Hi! I have a problem with `auto-inactive` option.

The issue is following:
* we're using one docker-based env for testing purposes created for feature branches
* when I'm pushing a code and build passed successfully, I got an info about new env available it's build using PR's number so it's more like `${PR_NUMBER}.our_test_domain.com`
* when someone else pushes the code to another feature branch, my deployment (from another but still active branch) is marked as inactive so in practice sometimes even after a few minutes I cannot easily get env URL.

My code is following:
```
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: "https://${{ steps.find_pr.outputs.number }}.${{ env.DOMAIN_ENDING }}"
          state: "success"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
```

I tried with the `ref` as I saw some suggestions  in the issues here but it seems the only option to not get some builds inactive (so to still see the address of the test env) is to turn off `auto-inactive` option but that's something I'd like to avoid. Is there any other way to not change environment name and differentiate deployments per branch to mark as inactive only these I really want to "close"?
