### ISSUE TITLE
Http validation failed on in_progress status

### ISSUE THREAD

**Issue by sergeysova** [chrnorm/deployment-status#8]
```yaml
      - uses: chrnorm/deployment-status@releases/v1
        name: Deployment progress
        with:
          token: '${{ github.token }}'
          environment: development
          state: in_progress
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
```

https://github.com/authmenow/releases/runs/630056476?check_suite_focus=true

I think it is because `in_progress` status requires custom media type: https://developer.github.com/v3/repos/deployments/#parameters-2
